import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ExternalLink } from 'lucide-react';
import { mockLeads } from '../../../data/mock-leads';
import { calculateScore } from '../../../lib/scoring';
import { PriorityBadge } from '../../../components/PriorityBadge';
export default function LeadDetailPage({ params }: { params: { id: string } }) {
  const lead = mockLeads.find((item) => item.id === params.id); if (!lead) notFound(); const score = calculateScore(lead);
  return <main className="mx-auto max-w-5xl px-6 py-10"><Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-600"><ArrowLeft size={16} /> Voltar</Link><div className="rounded-3xl border bg-white p-8 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="text-sm font-semibold uppercase tracking-widest text-brand-600">Diagnóstico 360</p><h1 className="mt-2 text-3xl font-bold text-slate-950">{lead.companyName}</h1><p className="mt-2 text-slate-600">{lead.city}/{lead.state} · {lead.niche}</p></div><div className="text-left md:text-right"><p className="text-4xl font-black text-slate-950">{lead.score360}</p><PriorityBadge priority={lead.priority} /></div></div><div className="mt-8 grid gap-4 md:grid-cols-2"><Info title="Google" value={`${lead.googleRating?.toFixed(1)} ★ / ${lead.googleReviews} avaliações`} /><Info title="Site" value={lead.website || 'Não encontrado'} /><Info title="Instagram" value={lead.instagram || 'Não encontrado'} /><Info title="Anúncios" value={lead.adsDetected ? 'Sinais encontrados' : 'Não identificado'} /><Info title="WhatsApp" value={lead.hasWhatsApp ? 'Encontrado' : 'Não encontrado'} /><Info title="Tracking" value={lead.hasTracking ? 'Encontrado' : 'Não encontrado'} /></div><div className="mt-8 grid gap-4 md:grid-cols-5"><ScoreBox title="Potencial" value={score.businessPotential} max={25} /><ScoreBox title="Dor digital" value={score.digitalPain} max={25} /><ScoreBox title="Maturidade" value={score.commercialMaturity} max={20} /><ScoreBox title="Contato" value={score.contactEase} max={15} /><ScoreBox title="Investimento" value={score.investmentSignals} max={15} /></div><section className="mt-8 rounded-2xl bg-slate-50 p-5"><h2 className="text-lg font-bold text-slate-950">Principal dor</h2><p className="mt-2 text-slate-700">{lead.mainPain}</p><h2 className="mt-5 text-lg font-bold text-slate-950">Oferta sugerida</h2><p className="mt-2 text-slate-700">{lead.suggestedOffer}</p></section><section className="mt-8 rounded-2xl border border-brand-100 bg-brand-50 p-5"><h2 className="text-lg font-bold text-brand-900">Mensagem sugerida</h2><pre className="mt-3 whitespace-pre-wrap rounded-xl bg-white p-4 text-sm leading-6 text-slate-700">{lead.suggestedMessage}</pre></section><div className="mt-8 flex flex-wrap gap-3">{lead.googleMapsUrl ? <a href={lead.googleMapsUrl} target="_blank" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 font-semibold text-slate-700 hover:bg-slate-50">Google Maps <ExternalLink size={16} /></a> : null}<a href={`https://wa.me/${lead.phone?.replace(/\D/g, '')}`} target="_blank" className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2 font-semibold text-white hover:bg-brand-700">Chamar no WhatsApp</a></div></div></main>;
}
function Info({ title, value }: { title: string; value: string }) { return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1 font-semibold text-slate-950">{value}</p></div>; }
function ScoreBox({ title, value, max }: { title: string; value: number; max: number }) { return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1 text-2xl font-black text-slate-950">{value}<span className="text-sm font-medium text-slate-400">/{max}</span></p></div>; }
